[workspace]
members = ["crates/stalkshift-capture", "crates/stalkshift-hid", "crates/stalkshift-core", "crates/stalkshift"]
resolver = "3"

[workspace.package]
version = "0.1.0-dev"
edition = "2024"
license = "MIT"
repository = "https://github.com/Moltenship/stalkshift"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
stalkshift-capture = { path = "crates/stalkshift-capture" }
stalkshift-hid = { path = "crates/stalkshift-hid" }
stalkshift-core = { path = "crates/stalkshift-core" }

[workspace.lints.rust]
unsafe_code = "forbid"
